### ISSUE TITLE
How to port it to html5?

### ISSUE THREAD

**Issue by TylerTehNub** [SanicBTW/FNF-PsychEngine-0.3.2-hotfix#21]

**Comment by SanicBTW** [comment]
I currently have a CI copied from Kade Engine, you can check the Actions tab and the HTML5 Build CI action, select the latest run and you have the [artifact available to download](https://github.com/SanicBTW/FNF-PsychEngine-0.3.2-hotfix/suites/4555177331/artifacts/122342973) but if you want to compile it you must follow the tutorial on how to set up haxe, haxeflixel and that stuff, if you already have haxe set up you can clone this repo and open a terminal and type "lime build html5" and in the export folder inside release and html5 you should have the html5 build as a bunch of files, you can make a zip file from those files, if you want more help you can add me on discord (sanco#0217)
