### ISSUE TITLE
is this gonna be a web port??

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [SanicBTW/FNF-PsychEngine-0.3.2-hotfix#22]

**Comment by SanicBTW** [comment]
I was literally doing that

**Comment by LEVIXDDLMAO** [comment]
its only loading to 13%

**Comment by SanicBTW** [comment]
Only loading at 13% because it's missing half of the files, I have to manually upload them because I don't have any other device that I can upload the files directly to the repo.

**Comment by LEVIXDDLMAO** [comment]
ohh i see if you like i an help

**Comment by SanicBTW** [comment]
Nah its fine, im gonna finish uploading all the stuff soon

**Comment by LEVIXDDLMAO** [comment]
ah okay

**Comment by SanicBTW** [comment]
Also this repo is meant to be only for web builds, can be built for desktop too but the main purpose of this its to port old mods to web but my work is amazingly trash

**Comment by SanicBTW** [comment]
BRO THIS THING ISNT PUSHING TO THE BRANCHHHHHHHHH

**Comment by SanicBTW** [comment]
Ok done, had to manually push it lol, haven't checked if it works or if it doesn't, but once the page is reloaded I will close the issue

**Comment by SanicBTW** [comment]
Stuck at 87%, I think its something related to flxg mouse

**Comment by SanicBTW** [comment]
Ok seems to be working now, enjoy!
