### ISSUE TITLE
is there a way to add ghost tapping and how do you change to f*cked diff

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [SanicBTW/FNF-PsychEngine-0.3.2-hotfix#23]

**Comment by LEVIXDDLMAO** [comment]
nevermind on the fucked diff 
i need to see how to turn on ghost tapping

**Comment by SanicBTW** [comment]
You can go to options and preferences and search the ghost tapping option which is disabled by default

**Comment by LEVIXDDLMAO** [comment]
ah thx

**Comment by LEVIXDDLMAO** [comment]
for some reason its not there

**Comment by LEVIXDDLMAO** [comment]
its not there even if i restart the game
