### ISSUE TITLE
can you add unloaded and  phantasm please??

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [SanicBTW/FNF-PsychEngine-0.3.2-hotfix#25]

**Comment by SanicBTW** [comment]
I would love to do that, unfortunately I spent a month trying to get Accelerant working, it works but it isn't completed yet, it would lag sometimes whenever the Change Character event happens and considering how much stuff Unloaded adds it would take me a lot of time including school and more, I haven't heard about Phantasm, so I have to kindly decline the petition for now. Sorry

**Comment by SanicBTW** [comment]
I think note splashes are enabled by default but that one is hidden in the settings too, my bad

**Comment by SanicBTW** [comment]
Done, everything should be fine now
