### ISSUE TITLE
can you  compile the newest psych engine to html5 please i really wanna play it

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [SanicBTW/FNF-PsychEngine-0.3.2-hotfix#27]

**Comment by LEVIXDDLMAO** [comment]
Well not 0.5.3b but 0.5.2h please? i couldn't do it

**Comment by SanicBTW** [comment]
Sure

**Comment by LEVIXDDLMAO** [comment]
thank you so much!

**Comment by SanicBTW** [comment]
Hey Im having a couple of issues with 0.5.2h source code, I thought about going to 0.5 or try with the latest source code

**Comment by LEVIXDDLMAO** [comment]
0.5.2h is the latest sorce code 0.5.3b is the apirl fools joke for shodow mario

**Comment by SanicBTW** [comment]
well not exactly, 0.5.2h is the latest version, commits exist after a new release, the 0.5.3b source code is in a different repo

**Comment by LEVIXDDLMAO** [comment]
so the latest version is 0.5.3b?

**Comment by LEVIXDDLMAO** [comment]
https://github.com/LEVIXDDLMAO/Html5-test here is the 0.5.2h i was trying to complie before apirl fools

**Comment by SanicBTW** [comment]
gonna do my thing then

**Comment by LEVIXDDLMAO** [comment]
if that dosen't work i got one more you can try

**Comment by LEVIXDDLMAO** [comment]
are you still gonna compile psych engine to html5?

**Comment by SanicBTW** [comment]
ye

**Comment by LEVIXDDLMAO** [comment]
and can you see if you keep the mod folder or something? im making a mod

**Comment by LEVIXDDLMAO** [comment]
have you done it yet?

**Comment by SanicBTW** [comment]
My bad bro, I was studying because I have an exam, I'm still up to make the port though I don't think that the mods folder is gonna work on a HTML5 target, I could try but I have no idea if it works, I will test it once I get a stable port of 0.5.2h

**Comment by SanicBTW** [comment]
My bad bro, I was studying because I have an exam, I'm still up to make the port though I don't think that the mods folder is gonna work on a HTML5 target, I could try but I have no idea if it works, I will test it once I get a stable port of 0.5.2h

**Comment by LEVIXDDLMAO** [comment]
No your fine the mod folder isn't really important so you do have to add it

**Comment by SanicBTW** [comment]
Gonna work on it today (in a few hours or so) I hope I can have it around at the end of the day

**Comment by LEVIXDDLMAO** [comment]
okay take your time

**Comment by LEVIXDDLMAO** [comment]
Yo long time no see

**Comment by SanicBTW** [comment]
Sup

**Comment by LEVIXDDLMAO** [comment]
How have you been?

**Comment by SanicBTW** [comment]
Dying

**Comment by LEVIXDDLMAO** [comment]
why?
