### ISSUE TITLE
your sleeping prob but

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [SanicBTW/FNF-PsychEngine-0.3.2-hotfix#32]

**Comment by LEVIXDDLMAO** [comment]
me and memehoovy got indie cross html to port

**Comment by SanicBTW** [comment]
Cool

**Comment by LEVIXDDLMAO** [comment]
but, how do i change the ogg to be mp3 for html?

**Comment by SanicBTW** [comment]
wdym

**Comment by SanicBTW** [comment]
but why would you do that tho, converting ogg to mp3 can be hell sometimes and if its fnf its just better to stick with ogg file format, i use ogg on all my html ports and engines because its easier and the filesize its smaller

**Comment by LEVIXDDLMAO** [comment]
i used #if web "ogg"

**Comment by SanicBTW** [comment]
just put "ogg"; and nothing else
